### ISSUE TITLE
Can't install Scalr 5.0.1 using new installer

### ISSUE THREAD

**Issue by beramb** [Scalr/installer-ng#103]
Hello, 
I'm getting error when trying to install specific version of Scalr (v5.0.1)
I'm using scalr-manage wrapper (v 7.9.3), and Ubuntu 12.04 
I've done "scalr-manage configure", and then manually changed the Scalr version to 5.0.1 in /etc/scalr.json
Then, I launch "scalr-manage install", and getting the following error. 
```
...
...
...

Recipe: scalr-core::package
  * apt_package[bash] action install (up to date)
  * apt_package[coreutils] action install (up to date)
  * apt_package[git] action install
    - install version 1:1.7.9.5-1ubuntu0.1 of package git
  * ruby_block[load ssh key] action run
    - execute the ruby block load ssh key
  * deploy_revision[scalr] action deploy
    - create new directory /opt/scalr
    - create new directory /opt/scalr/shared
    * Unable to parse SHA reference for '5.0.1' in repository 'git://github.com/Scalr/scalr.git'. Verify your (case-sensitive) repository URL and revision.
    `git ls-remote 'git://github.com/Scalr/scalr.git' '5.0.1*'` output: 
    - remove failed deploy /opt/scalr/releases/
    ================================================================================
    Error executing action `deploy` on resource 'deploy_revision[scalr]'
    ================================================================================
    
    Chef::Exceptions::UnresolvableGitReference
    ------------------------------------------
    Unable to parse SHA reference for '5.0.1' in repository 'git://github.com/Scalr/scalr.git'. Verify your (case-sensitive) repository URL and revision.
    `git ls-remote 'git://github.com/Scalr/scalr.git' '5.0.1*'` output: 
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cookbooks/scalr-core/recipes/package.rb
    
     16: deploy_revision node[:scalr][:package][:name] do
     17:   repo              node[:scalr][:package][:repo]
     18:   deploy_to         node[:scalr][:package][:deploy_to]
     19:   revision          node[:scalr][:package][:revision]
     20:   ssh_wrapper       git_ssh_wrapper
     21:   user              node[:scalr][:core][:users][:service]
     22:   group             node[:scalr][:core][:group]
     23:   rollback_on_error true
     24:   symlink_before_migrate.clear
     25:   create_dirs_before_symlink.clear
     26:   purge_before_symlink.clear
     27:   symlinks.clear
     28: end
     29: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cookbooks/scalr-core/recipes/package.rb:16:in `from_file'
    
    deploy_revision("scalr") do
      action :deploy
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      deploy_to "/opt/scalr"
      repository_cache "cached-copy"
      revision "5.0.1"
      rollback_on_error true
      remote "origin"
      scm_provider Chef::Provider::Git
      keep_releases 5
      enable_checkout true
      checkout_branch "deploy"
      declared_type :deploy_revision
      cookbook_name :"scalr-core"
      recipe_name "package"
      repo "git://github.com/Scalr/scalr.git"
      git_ssh_wrapper "/var/chef/cookbooks/scalr-core/files/default/chef_ssh_deploy_wrapper.sh"
      user "root"
      group "scalr"
      shared_path "/opt/scalr/shared"
      destination "/opt/scalr/shared/cached-copy"
      current_path "/opt/scalr/current"
    end
    
Recipe: rackspace_timezone::_timezone
  * bash[dpkg-reconfigure tzdata] action run
Current default time zone: 'Etc/UTC'
Local time is now:      Thu Jan 15 09:54:27 UTC 2015.
Universal Time is now:  Thu Jan 15 09:54:27 UTC 2015.


    - execute "bash"  "/tmp/chef-script20150115-4571-d3x68k"
Recipe: ntp::default
  * service[ntp] action restart
    - restart service service[ntp]
Recipe: mysql::server
  * mysql_service[default] action restart (up to date)

Running handlers:
Running handlers complete
Chef Client failed. 76 resources updated in 168.474749021 seconds
[2015-01-15 09:54:30,183:ERROR] [target.py:124] [scalr_manage.library.install.target] Installation failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scalr_manage/library/install/target.py", line 121, in __call__
    step(args, work_dir, http_download)
  File "/usr/local/lib/python2.7/dist-packages/scalr_manage/library/install/target.py", line 85, in install_scalr
    subprocess.check_call([CHEF_SOLO_BIN, "--config", os.path.join(work_dir, constant.SOLO_RB_FILE)])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['chef-solo', u'--config', '/tmp/tmpIBNlAe/solo.rb']' returned non-zero exit status 1


Whoops! It looks like the installer hit a snag
Please file an issue to get support: https://github.com/scalr/installer-ng/issues
Please include the installer log file in your bug report: /var/log/scalr-install.log
If this looks like a temporary issue, consider re-executing the installer command that failed by running
  /usr/local/bin/scalr-manage install
```

**Comment by krallin** [comment]
Hi there,

The version needs to match a ref that exists in the Scalr repo. The ref can be either a tag or a branch. 

The tag for 5.0.1 is `v5.0.1`, and the branch for Scalr 5.0 is `5.0`. You'll have to use either one of those values for it to work (just `5.0.1` does not exist).

You can edit `/etc/scalr.json` to change the version (it should be the `scalr.package.revision` key). Make sure you use a matching `scalr.package.version` to inform the installer of what version you are deploying.

Hope this helps. Just let me know if you run into trouble again (I'll close this ticket for now, but I'm still subscribed to it).

Cheers,

**Comment by beramb** [comment]
yes, this helped, Thanks!

**Comment by krallin** [comment]
Great! You're welcome, of course.

Cheers,
